### ISSUE TITLE
Sourcear contenido mas diverso (html & css, react, ...)

### ISSUE THREAD

**Issue by merunga** [Laboratoria/gym#146]
https://www.w3schools.com/css/exercise.asp
https://github.com/Laboratoria/html-css-exercises#juegos
https://cssbattle.dev/
https://100dayscss.com
https://css-tricks.com/front-end-challenges/
https://css-challenges.com/#

**Comment by reloadercf** [comment]
@merunga  agrego un repo que encontre:
https://github.com/florinpop17/app-ideas
