### ISSUE TITLE
Agregar solucion alternativa para ejercicio newbie middleThree

### ISSUE THREAD

**Issue by ssinuco** [Laboratoria/gym#159]
Ya hay una solucion imperativa, agregar una solucion alternativa.

**Comment by reloadercf** [comment]
@ssinuco ¿cual es el status de este issue??

**Comment by reloadercf** [comment]
@ssinuco creo que este issue puede ser migrado al repo de soluciones https://github.com/Laboratoria/gym-solutions/issues/18
