### ISSUE TITLE
Documentar cuando ocurren mock interviews

### ISSUE THREAD

**Issue by icarito** [Laboratoria/gym#287]

**Comment by icarito** [comment]
Debería salir en los README de la sesión

**Comment by icarito** [comment]
Sesión 14 ~ 16 y documentar lo que ocurre ahí

**Comment by icarito** [comment]
Aquí un video compartido por @reloadercf https://www.youtube.com/watch?v=v7wKOdz1bZ8

**Comment by icarito** [comment]
@MarciaMillanao @ssinuco @reloadercf uds tienen un borrador que podamos colocar por acá? :pray: 
Luna y Deisy lo van a necesitar.

**Comment by icarito** [comment]
@unjust ha pedido que aceleremos resolver esto :pray:

**Comment by unjust** [comment]
Perdon la acceleración 😉 Voy a apuntar algunos temas/problemas que nos pasan, y impulso mi feedback.

* Pensaba que nuestro primer mock interview seria con un coach, con todos mirando y espacio para preguntas y feedback (como los anteriores). Pero nos paso [este documento](https://docs.google.com/document/d/1gTZW--ZQZuIq0V7FHLiRUYU2-75QwSV49DoPcImCm3E/edit) y dijo que esta es el la dinamica ahora.
* Decidimos que para el primer espacio, mejor que tiene toda a ellas juntas en un espacio con un solo persona haciendo la entrevista para tengan una misma experiencia base. Elegimos usar una egresada porque el documento dice que usan egresadas. Planeamos que el segundo mock interview puede ser en salitas con algunas egresadas, como dice el documento.
* Hoy nos avisa que que la segunda entrevista debe ser como la primera que hicimos (todos juntos) pero con un coach. (Estoy acostumbrada a esta manera) Tambien escuchamos que los espacios con egresadas serian mas adelante en el gim - y a estas se llaman "mock mock interviews" porque involucran egresadas.

Seria bueno definir las dinamicas de cada mock espacio - por ejemplo el primero es con un coach y todos mirando, el segundo espacio esta en salitas con egresadas, etc. Y en mi opinion, seria mas clara llamar todos "mock interviews tech" (o cualquier nombre clara). La diferencia entre _mock_ y _mock mock_ es confuso.

En el doc/Coda necesitamos decir clara que las semanas estan eligido con/depende en job application en cada cohort. (_En nuestro caso tambien habia confusion sobre eso_) 

Espero que nuestros problemas ayudan las soluciónes!

**Comment by icarito** [comment]
De acuerdo a conversación con Sam P. - debería empezar a suceder en la semana 8 - documentar esto y empezar a usar en DEV009
