### ISSUE TITLE
Encontrar ejercicios de LMS

### ISSUE THREAD

**Issue by icarito** [Laboratoria/gym#291]
No encuentro el link a los ejercicios del LMS. Nos propusimos cada uno de nosotros traer uno de ellos para darles a las egresadas para las simulaciones de entrevistas técnicas.

**Comment by reloadercf** [comment]
@icarito para que puedas acceder a los ejercicios debes ser coach de alguna cohort y esa cohort debe tener cargados los tópicos que incluyen los ejercicios.
Te acabo de agregar a la cohort cdmx013 como coach y acabo de cargar algunos ejercicios que me ayudo a Mapear @GenesisMauries

**Comment by reloadercf** [comment]
@icarito tal vez estos igual pueden ser útiles https://curriculum.laboratoria.la/es/js/gym
