### ISSUE TITLE
Links a Kahoot en los README de sesión

### ISSUE THREAD

**Issue by msantelices** [Laboratoria/gym#313]
Actualmente los README de cada sesión contienen el link al Kahoot correspondiente, sin embargo, es posible ingresar a ese link y ver todas las preguntas y respuestas con anticipación.

IDEA: Quitar los Kahoot del README de sesión y pasarlos al repositorio de soluciones. Compartir los links una vez terminada la sesión de Gym

¿Comentarios, sugerencias, algo?

**Comment by reloadercf** [comment]
Hola @msantelices  actualmente esta pensado para que el [origen](https://github.com/Laboratoria/gym/tree/main/sessions) de cada session encontrado en `main` sea una herramienta a lxs coaches que quieran correr esa sesión, y la idea es que cuando compartas la branch con 'dev002' la session no incluya el kahoot, pero después de haber ejecutado el kahoot en vivo, podemos compartir el kahoot con las estudiantes sin ningún problema; 
te comparto las [sessiones](https://github.com/Laboratoria/CDMX013-gym) que usamos en CDMX013 por si quieres mirar como se integraron los commits!

**Comment by reloadercf** [comment]
@icarito igual esto lo podemos volver a retomar en un futuro, por el momento voy a ir levantando una emoji encuesta para ir sondeando.

**Comment by moniyama** [comment]
sobre eso, a mi los links de kahoots en repo son utiles para organización de la equipo/persona que va a tocar el espacio

**Comment by icarito** [comment]
Pensamos que no es un problema tener los kahoot en el repo.
