### ISSUE TITLE
ejercicios star lover warmup & star-lovers-challenge not working - sesion 12 

### ISSUE THREAD

**Issue by moniyama** [Laboratoria/gym#361]
en SAP010, las estudiantes han notado que el link de los ejercicios están rotos:
- star lovers warmup: https://lab.cs50.io/Laboratoria/gym-exercises/main/star-lovers-warmup/
- star lovers challenge: https://lab.cs50.io/Laboratoria/gym-exercises/main/star-lovers-challenge/

Los ejercicios están en la sesión 12

**Comment by icarito** [comment]
🤦‍♂️
Confirmado, os projetos com CS50 estão quebrados...
--
Sebastian Silva
(él / he)
Jardinero de Sistemas
