### ISSUE TITLE
Unificar documentación de Entrevista

### ISSUE THREAD

**Issue by icarito** [Laboratoria/gym#367]
[Guía para entrevista GYM](https://github.com/Laboratoria/gym/blob/main/docs/interviews/first-tech-mock-interview/README-Interviewer.md)
[Sesión 11 Tech interview practice](https://github.com/Laboratoria/gym/blob/DEV005/sessions/session-11.md)
[Guía minuto a minuto de cómo ejecutar la primera entrevista](https://github.com/Laboratoria/gym/blob/main/docs/interviews/first-tech-mock-interview/README-Coach.md)

(reportado por Sam)

**Comment by icarito** [comment]
se puede usar la misma documentación para Egresadas / Coach / etc?

**Comment by icarito** [comment]
Feedback de Jorge - documento por sesión de entrevista

**Comment by icarito** [comment]
También incluir tener suplentes

**Comment by AlexisJoselyn** [comment]
Estoy de acuerdo con tener diferentes ejercicios disponibles por sesión dado que los contextos según la semana es similar en cada cohort. Me sumo también a las preguntas técnicas, porque usualmente son los objetivos que más patean, por ejemplo scope de variables.

**Comment by icarito** [comment]
@AlexisJoselyn muchas gracias por tu aporte, de acuerdo a lo conversado hoy podemos usar la comunicación modelo que propones, te agradecemos la propuesta de incluir una plantilla de comunicación con el entrevistador.

**Comment by icarito** [comment]
Gracias @AlexisJoselyn ! Integrado en #373
