### ISSUE TITLE
Comentar soluciones

### ISSUE THREAD

**Issue by merunga** [Laboratoria/gym#92]
Si la idea es que, luego de cada sesión compartamos las soluciones con las estudiantes, quizás tendríamos que revisitar las soluciones de los ejercicios ya garantizarnos de explicar lo que está sucediendo, y poder darle más valor a ese recurso.

Un ejemplo de una solucion q no es facil de entender podria ser [`all-rotatios`](https://github.com/Laboratoria/gym/blob/main/exercises/all-rotations/solutions/rotation.declarative.js) (@ssinuco)

Una solucion declarativa, no necesariamente tiene q ser ser criptica o estar expresada en una sola línea linea de llamadas encadenadas... se puede dar un poco mas de contexto, por ejemplo pasar de:
```js
function rotate(str, position) {
  return str.slice(position).concat(str.slice(0, position));
}

function leftRotations(str) {
  return Array.from(str).map((_, index) => rotate(str, index));
}

function rightRotations(str) {
  return Array.from(str).map((_, index) => rotate(str, str.length - index));
}
```
a algo asi (+ comentarios)

```js
function rotate(str, position) {
  const delta = str.slice(0, position);
  return str.slice(position).concat(delta);
}

function leftRotations(str) {
  const arr = Array.from(str);
  return arr.map((_, index) => rotate(str, index));
}

function rightRotations(str) {
  const arr = Array.from(str);
  return arr.map((_, index) => {
    const indexRight = arr.length - index;
    return rotate(str, indexRight);
  });
}
```

@ssinuco @oxfist creo q no está documentado en ningún lugar y tampoco se si se los he comentado a ambos, pero para cada ejecucion, hay una version de este repo publica para las estudiantes, donde se registrando las sesiones.

@oxfist vi que para [SCL017](https://github.com/Laboratoria/SCL017-gym) tu ya tienes uno. La diferencia es que, por ejemplo en MEX011, luego de cada sesión, [se publican las soluciones](https://github.com/Laboratoria/CDMX011-gym/tree/master/session-07/exercises/odd-or-even/solutions).

Qué opinan?

**Comment by icarito** [comment]
soluciones en gym-solutions
